spring:
  datasource:
    url: jdbc:mysql://localhost/spring_in_action
    username: liuxu
    password: liuxu
    #initialization-mode: always
    schema:
      - classpath:schema.sql
    #data:
    #  - classpath:data.sql