server:
  port: 8899

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuxuhelloworld/learning-spring
          search-paths: taco-cloud-microservice/taco-cloud-config